# Tentativa de entender os cálculos

In [1]:
import numpy as np

In [2]:
def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1 / (1 + np.exp(-x))

### Separei o Foward do Backward 

In [3]:
x = np.array([0.5, 0.1, -0.2]) # input layer
target = 0.6 # output
learnrate = 0.5

weights_input_hidden = np.array([[0.5, -0.6],
                                 [0.1, -0.2],
                                 [0.1, 0.7]])  # pesos do input layer para hidden layer 0

weights_hidden_output = np.array([0.1, -0.3])  # pesos do hidden layer 0 para output

## Forward pass
hidden_layer_input = np.dot(x, weights_input_hidden) # hidden layer 0
hidden_layer_output = sigmoid(hidden_layer_input) # hiddenlayer 0 com a função de ativação

output_layer_in = np.dot(hidden_layer_output, weights_hidden_output) # output
output = sigmoid(output_layer_in) # output com a função de ativação

### Uma rede neural com:
                3 neuronios de input
                2 neuronios de hidden layer
                1 neuronio de output

In [4]:
print(x,x.shape)

[ 0.5  0.1 -0.2] (3,)


In [5]:
print(weights_input_hidden,weights_input_hidden.shape)

[[ 0.5 -0.6]
 [ 0.1 -0.2]
 [ 0.1  0.7]] (3, 2)


In [6]:
print (weights_hidden_output, weights_hidden_output.shape)

[ 0.1 -0.3] (2,)


In [7]:
print(hidden_layer_input,hidden_layer_input.shape)

[ 0.24 -0.46] (2,)


### Tentativa de fazer o backprapagation
                    Não consegui entender muito bem se devemos aplicar os pesos para o calculo do gradiente.
                    No datacamp não ficou claro para mim, eu fiz sem eles.

In [8]:
x_sigmoid= sigmoid(x)

In [9]:
## Backwards pass
## TODO: Calculate output error
error = output - target

# TODO: Calculate error term for output layer
output_error_term = hidden_layer_output * error * (1 - output) # gradiente do outpu para hidden layer

# TODO: Calculate error term for hidden layer
hidden_error_term = output_error_term  * x[:, None] * (1 - hidden_layer_output) # gradiente do hidden layer para output

# TODO: Calculate change in weights for hidden layer to output layer  # atualização do peso do output para hidden layer
delta_w_h_o =weights_hidden_output - (output_error_term * learnrate)

# TODO: Calculate change in weights for input layer to hidden layer  # atualização do peso do hidden layer para input
delta_w_i_h = weights_input_hidden - (hidden_error_term * learnrate)

print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_h)


Change in weights for hidden layer to output layer:
[ 0.11657921 -0.28853714]
Change in weights for input layer to hidden layer:
[[ 0.5036498  -0.59648655]
 [ 0.10072996 -0.19929731]
 [ 0.09854008  0.69859462]]


#### obs: não sei se usei a derivada da função de ativação na camada correta para o calculo dos gradientes 

### Utilzação dos novos pesos 

In [10]:
hidden_layer_input2 = np.dot(x, delta_w_i_h) # hidden layer 0
hidden_layer_output2 = sigmoid(hidden_layer_input2) # hiddenlayer 0 com a função de ativação

output_layer_in2 = np.dot(hidden_layer_output2, delta_w_h_o) # output
output2 = sigmoid(output_layer_in2) # output com a função de ativação

In [11]:
error2 = output2 - target

In [12]:
error2

-0.11162046618389443

In [13]:
error

-0.11502656915007464